import styles from "../styles/Home.module.scss"
import Head from 'next/head'
import NavBar from "./NavBar";

function Wrapper({ children }) {
    return (
        <>
            <Head>
                <title>News And Blog</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar />
            <main className={styles.container}>
                { children }
            </main>
        </>
    )
}
export default Wrapper;